# Generated by Django 4.2.5 on 2023-09-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelmodel',
            name='name',
            field=models.CharField(max_length=127, null=True, unique=True),
        ),
    ]
