# Generated by Django 4.2.5 on 2023-09-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '__first__'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='labels', to='task_manager.labelmodel'),
        ),
    ]
