# Generated by Django 4.2.5 on 2023-10-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(error_messages={'unique': 'Such a task already exists'}, help_text='<i>Обязательное поле</i>', max_length=127, unique=True, verbose_name='Name'),
        ),
    ]
