name: Python CI

on:
  - push
  - pull_request

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        # Clone the repository.
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install poetry
          make install

      - name: Run linter
        run: |
          make lint

      - name: Run tests
        run: |
          make test

        # Run pytest via: make test-coverage.
        # Publishing code test on Code Climate.
      - name: Test & publish code coverage for Code Climate
        uses: paambaati/codeclimate-action@v3.0.0
        if: github.ref_name == 'main'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true