# Generated by Django 4.2.5 on 2023-09-30 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_taskmodel_name'),
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatusModel',
            new_name='Status',
        ),
    ]
